// S&P MidCap 400 constituents, [ticker, name], so the market-movers feed in
// api/sector-stocks.js scans sizable non-S&P 500 stocks too.
// Source: State Street MDY ETF daily holdings, as of 2026-10-08 —
// https://www.ssga.com/us/en/intermediary/library-content/products/fund-data/etfs/us/holdings-daily-us-en-mdy.xlsx
// The index rebalances quarterly; re-pull from that file every few months.
export const SP400 = [
  ["OKTA", "Okta"], ["FTI", "TechnipFMC"], ["NVT", "nVent Electric"], ["ATI", "ATI"],
  ["ENTG", "Entegris"], ["UTHR", "United Therapeutics"], ["MTSI", "MACOM Technology Solutions"], ["SNX", "TD SYNNEX"],
  ["XPO", "XPO"], ["USFD", "US Foods"], ["THC", "Tenet Healthcare"], ["ROKU", "Roku"],
  ["RS", "Reliance"], ["NTNX", "Nutanix"], ["RGLD", "Royal Gold"], ["CRS", "Carpenter Technology"],
  ["PR", "Permian Resources"], ["WWD", "Woodward"], ["CW", "Curtiss-Wright"], ["DINO", "HF Sinclair"],
  ["ROIV", "Roivant Sciences"], ["ITT", "ITT"], ["LSCC", "Lattice Semiconductor"], ["DT", "Dynatrace"],
  ["MKSI", "MKS"], ["SMTC", "Semtech"], ["FN", "Fabrinet"], ["OVV", "Ovintiv"],
  ["BURL", "Burlington Stores"], ["WCC", "WESCO International"], ["CDE", "Coeur Mining"], ["EWBC", "East West Bancorp"],
  ["RGA", "Reinsurance Group of America"], ["TLN", "Talen Energy"], ["CLH", "Clean Harbors"], ["STRL", "Sterling Infrastructure"],
  ["TOST", "Toast"], ["RBA", "RB Global"], ["RBC", "RBC Bearings"], ["APG", "APi"],
  ["SN", "SharkNinja"], ["SITM", "SiTime"], ["PFGC", "Performance Food"], ["ARMK", "Aramark"],
  ["EXEL", "Exelixis"], ["JAZZ", "Jazz Pharmaceuticals Public Limited"], ["WPC", "W. P. Carey"], ["ONTO", "Onto Innovation"],
  ["NBIX", "Neurocrine Biosciences"], ["SGI", "Somnigroup International"], ["PNFP", "Pinnacle Financial Partners"], ["LECO", "Lincoln Electric"],
  ["JLL", "Jones Lang LaSalle"], ["NLY", "Annaly Capital Management"], ["RNR", "RenaissanceRe"], ["GWRE", "Guidewire Software"],
  ["DOCU", "DocuSign"], ["MEDP", "Medpace"], ["SUI", "Sun Communities"], ["EQH", "Equitable"],
  ["MTZ", "MasTec"], ["MLI", "Mueller Industries"], ["OHI", "Omega Healthcare Investors"], ["UNM", "Unum"],
  ["CACI", "CACI International"], ["BWXT", "BWX Technologies"], ["NXT", "Nextpower"], ["CSL", "Carlisle Companies"],
  ["RPM", "RPM International"], ["LAMR", "Lamar Advertising"], ["GGG", "Graco"], ["BJ", "BJ's Wholesale Club"],
  ["DTM", "DT Midstream"], ["TOL", "Toll Brothers"], ["BWA", "BorgWarner"], ["PEN", "Penumbra"],
  ["HALO", "Halozyme Therapeutics"], ["TTMI", "TTM Technologies"], ["TRU", "TransUnion"], ["AIT", "Applied Industrial Technologies"],
  ["DOCN", "DigitalOcean"], ["EHC", "Encompass Health"], ["MANH", "Manhattan Associates"], ["RMBS", "Rambus"],
  ["CCK", "Crown"], ["FIVE", "Five Below"], ["HUBS", "HubSpot"], ["ARW", "Arrow Electronics"],
  ["AEIS", "Advanced Energy Industries"], ["ELS", "Equity LifeStyle Properties"], ["AA", "Alcoa"], ["SANM", "Sanmina"],
  ["CORT", "Corcept Therapeutics Incorporated."], ["ELAN", "Elanco Animal Health"], ["HL", "Hecla Mining"], ["GLPI", "Gaming and Leisure Properties"],
  ["AR", "Antero Resources"], ["FHN", "First Horizon"], ["AHR", "American Healthcare REIT"], ["WTRG", "Essential Utilities"],
  ["VIAV", "Viavi Solutions"], ["COKE", "Coca-Cola Consolidated"], ["BTSG", "BrightSpring Health Services"], ["LFUS", "Littelfuse"],
  ["SEIC", "SEI Investments"], ["FORM", "FormFactor"], ["TXRH", "Texas Roadhouse"], ["RRX", "Regal Rexnord"],
  ["BMRN", "BioMarin Pharmaceutical"], ["KNX", "Knight-Swift Transportation"], ["SF", "Stifel Financial"], ["CNH", "CNH Industrial NV"],
  ["EGP", "EastGroup Properties"], ["SCI", "Service Corporation International"], ["AVTR", "Avantor"], ["ALLY", "Ally Financial"],
  ["MOG.A", "Moog"], ["GME", "GameStop"], ["RGEN", "Repligen"], ["AGNC", "AGNC Investment"],
  ["EVR", "Evercore"], ["CGNX", "Cognex"], ["MOH", "Molina Healthcare"], ["FNF", "Fidelity National Financial Inc. - FNF"],
  ["CG", "Carlyle"], ["DCI", "Donaldson Company"], ["CR", "Crane"], ["WSO", "Watsco"],
  ["AMG", "Affiliated Managers"], ["ENSG", "Ensign"], ["DAR", "Darling Ingredients"], ["AFG", "American Financial"],
  ["SSB", "SouthState Bank"], ["WTFC", "Wintrust Financial"], ["AMH", "American Homes 4 Rent"], ["NYT", "New York Times"],
  ["SOLS", "Solstice Advanced Materials"], ["WTS", "Watts Water Technologies"], ["RRC", "Range Resources"], ["OGE", "OGE Energy"],
  ["CFR", "Cullen/Frost Bankers"], ["UMBF", "UMB Financial"], ["PINS", "Pinterest"], ["OC", "Owens Corning"],
  ["TTC", "Toro"], ["CTVA", "Corteva"], ["ZION", "Zions Bancorporation NA"], ["SAIA", "Saia"],
  ["CRBG", "Corebridge Financial"], ["VMI", "Valmont Industries"], ["R", "Ryder System"], ["ALSN", "Allison Transmission"],
  ["AYI", "Acuity"], ["DKS", "Dick's Sporting Goods"], ["FLS", "Flowserve"], ["WMS", "Advanced Drainage Systems"],
  ["PBF", "PBF Energy"], ["BAH", "Booz Allen Hamilton"], ["VOYA", "Voya Financial"], ["KRYS", "Krystal Biotech"],
  ["MUSA", "Murphy USA"], ["CYTK", "Cytokinetics"], ["ARWR", "Arrowhead Pharmaceuticals"], ["ORI", "Old Republic International"],
  ["TTEK", "Tetra Tech"], ["PRI", "Primerica"], ["AAL", "American Airlines"], ["IDCC", "InterDigital"],
  ["CTRE", "CareTrust REIT"], ["SPXC", "SPX Technologies"], ["FCFS", "FirstCash"], ["ONB", "Old National Bancorp"],
  ["DY", "Dycom Industries"], ["BRX", "Brixmor Property"], ["VNOM", "Viper Energy"], ["REXR", "Rexford Industrial Realty"],
  ["GMED", "Globus Medical"], ["ADC", "Agree Realty"], ["AVT", "Avnet"], ["EAT", "Brinker International"],
  ["COLB", "Columbia Banking System"], ["PB", "Prosperity Bancshares Inc.(R)"], ["CUBE", "CubeSmart"], ["UGI", "UGI"],
  ["KTOS", "Kratos Defense & Security Solutions"], ["OSK", "Oshkosh"], ["FR", "First Industrial Realty Trust"], ["CHRD", "Chord Energy"],
  ["HQY", "HealthEquity"], ["IDA", "IDACORP"], ["ATR", "AptarGroup"], ["NNN", "NNN REIT"],
  ["THG", "Hanover Insurance"], ["WAL", "Western Alliance Bancorp"], ["ACM", "AECOM"], ["CNM", "Core & Main"],
  ["NFG", "National Fuel Gas"], ["ALV", "Autoliv"], ["SLAB", "Silicon Laboratories"], ["CART", "Maplebear"],
  ["CBSH", "Commerce Bancshares"], ["KNSL", "Kinsale Capital"], ["KEX", "Kirby"], ["TKR", "Timken"],
  ["SSD", "Simpson Manufacturing Co."], ["AM", "Antero Midstream"], ["AXTA", "Axalta Coating Systems"], ["CMC", "Commercial Metals"],
  ["CLF", "Cleveland-Cliffs"], ["STAG", "STAG Industrial"], ["MP", "MP Materials"], ["NEU", "NewMarket"],
  ["FLR", "Fluor"], ["HLI", "Houlihan Lokey"], ["JEF", "Jefferies Financial"], ["NOV", "NOV"],
  ["QLYS", "Qualys"], ["H", "Hyatt Hotels"], ["BIO", "Bio-Rad Laboratories"], ["LNTH", "Lantheus"],
  ["CHE", "Chemed"], ["PCTY", "Paylocity"], ["VICR", "Vicor"], ["ENS", "EnerSys"],
  ["MSA", "MSA Safety"], ["BRKR", "Bruker"], ["HXL", "Hexcel"], ["FAF", "First American Financial"],
  ["MTDR", "Matador Resources"], ["LAD", "Lithia Motors"], ["AMKR", "Amkor Technology"], ["AGCO", "AGCO"],
  ["ANF", "Abercrombie & Fitch"], ["CVLT", "Commvault Systems"], ["ELF", "e.l.f. Beauty"], ["UBSI", "United Bankshares"],
  ["SFM", "Sprouts Farmers Market"], ["ST", "Sensata Technologies"], ["DUOL", "Duolingo"], ["FNB", "F.N.B."],
  ["VLY", "Valley National Bancorp"], ["SWX", "Southwest Gas"], ["INGR", "Ingredion"], ["M", "Macy's"],
  ["TEX", "Terex"], ["AAON", "AAON"], ["HIMS", "Hims & Hers Health"], ["HR", "Healthcare Realty Trust"],
  ["TXNM", "TXNM Energy"], ["LEA", "Lear"], ["BKH", "Black Hills"], ["LSTR", "Landstar System"],
  ["GATX", "GATX"], ["HWC", "Hancock Whitney"], ["MTG", "MGIC Investment"], ["ESNT", "Essent"],
  ["CRUS", "Cirrus Logic"], ["CAVA", "CAVA"], ["IESC", "IES"], ["CROX", "Crocs"],
  ["GBCI", "Glacier Bancorp"], ["EXLS", "ExlService"], ["WEX", "WEX"], ["WFRD", "Weatherford International"],
  ["BSY", "Bentley Systems"], ["VAL", "Valaris"], ["ULS", "UL Solutions"], ["HRB", "H&R Block"],
  ["SAIC", "Science Applications International"], ["PATH", "UiPath"], ["ORA", "Ormat Technologies"], ["WH", "Wyndham Hotels & Resorts"],
  ["HAE", "Haemonetics"], ["VNO", "Vornado Realty Trust"], ["G", "Genpact"], ["HOMB", "Home BancShares"],
  ["POR", "Portland General Electric"], ["MSM", "MSC Industrial Direct Co."], ["GXO", "GXO Logistics"], ["OLLI", "Ollie's Bargain Outlet"],
  ["MTN", "Vail Resorts"], ["AVAV", "AeroVironment"], ["MUR", "Murphy Oil"], ["NJR", "New Jersey Resources"],
  ["RLI", "RLI"], ["BROS", "Dutch Bros"], ["NOVT", "Novanta"], ["RYN", "Rayonier"],
  ["EXP", "Eagle Materials"], ["GAP", "Gap"], ["SHC", "Sotera Health"], ["SIGI", "Selective Insurance"],
  ["CNX", "CNX Resources"], ["CELH", "Celsius"], ["CHDN", "Churchill Downs"], ["CNO", "CNO Financial"],
  ["FND", "Floor & Decor"], ["SIRI", "SiriusXM"], ["DBX", "Dropbox"], ["VFC", "V.F."],
  ["KRG", "Kite Realty Group Trust"], ["SBRA", "Sabra Health Care REIT"], ["SON", "Sonoco Products"], ["APPF", "AppFolio"],
  ["MAT", "Mattel"], ["NXST", "Nexstar Media"], ["FBIN", "Fortune Brands Innovations"], ["ASB", "Associated Banc-Corp"],
  ["SYNA", "Synaptics"], ["OPCH", "Option Care Health"], ["SR", "Spire"], ["ALGM", "Allegro MicroSystems"],
  ["NWE", "NorthWestern Energy"], ["CUZ", "Cousins Properties"], ["OZK", "Bank OZK"], ["OGS", "ONE Gas"],
  ["TREX", "Trex Company"], ["SARO", "StandardAero"], ["GNTX", "Gentex"], ["STWD", "Starwood Property Trust"],
  ["KBR", "KBR"], ["ALK", "Alaska Air"], ["CHWY", "Chewy"], ["VNT", "Vontier"],
  ["MIDD", "Middleby"], ["WMG", "Warner Music"], ["SLM", "SLM"], ["BDC", "Belden"],
  ["UFPI", "UFP Industries"], ["BCO", "Brink's"], ["LPX", "Louisiana-Pacific"], ["LIVN", "LivaNova Plc"],
  ["EPR", "EPR Properties"], ["LOPE", "Grand Canyon Education"], ["FFIN", "First Financial Bankshares"], ["ACI", "Albertsons Companies"],
  ["RYAN", "Ryan Specialty"], ["AN", "AutoNation"], ["BC", "Brunswick"], ["TCBI", "Texas Capital Bancshares"],
  ["FHI", "Federated Hermes"], ["KRC", "Kilroy Realty"], ["VVV", "Valvoline"], ["CBT", "Cabot"],
  ["MORN", "Morningstar"], ["GHC", "Graham"], ["TNL", "Travel + Leisure"], ["FCN", "FTI Consulting"],
  ["ESAB", "ESAB"], ["CDP", "COPT Defense Properties"], ["AVNT", "Avient"], ["DOCS", "Doximity"],
  ["PVH", "PVH"], ["IBOC", "International Bancshares"], ["NVST", "Envista"], ["BILL", "BILL"],
  ["BBWI", "Bath & Body Works"], ["PAG", "Penske Automotive"], ["BYD", "Boyd Gaming"], ["DLB", "Dolby Laboratories"],
  ["IRT", "Independence Realty Trust"], ["THO", "Thor Industries"], ["FLG", "Flagstar Bank National Association"], ["HLNE", "Hamilton Lane"],
  ["EXPO", "Exponent"], ["PLNT", "Planet Fitness"], ["ASH", "Ashland"], ["WING", "Wingstop"],
  ["SLGN", "Silgan"], ["PEGA", "Pegasystems"], ["OLED", "Universal Display"], ["MMS", "MAXIMUS"],
  ["PK", "Park Hotels & Resorts"], ["KNF", "Knife River"], ["YETI", "YETI"], ["PII", "Polaris"],
  ["BHF", "Brighthouse Financial"], ["HOG", "Harley-Davidson"], ["POST", "Post"], ["KBH", "KB Home"],
  ["KD", "Kyndryl Holdings Incorporation"], ["GPK", "Graphic Packaging"], ["PSN", "Parsons"], ["CXT", "Crane NXT"],
  ["VC", "Visteon"], ["SMG", "Scotts Miracle-Gro"], ["FOUR", "Shift4 Payments"], ["EEFT", "Euronet Worldwide"],
  ["CHH", "Choice Hotels International"], ["WLK", "Westlake"], ["IPGP", "IPG Photonics"], ["GEF", "Greif"],
  ["MZTI", "Marzetti"], ["HGV", "Hilton Grand Vacations"], ["CAR", "Avis Budget"], ["WHR", "Whirlpool"],
  ["RH", "RH"], ["XRAY", "DENTSPLY SIRONA"], ["PPC", "Pilgrim's Pride"], ["COLM", "Columbia Sportswear"],
];
