// Auto-generated from ESPN's public /teams endpoint (site.api.espn.com) — 2026-09-15.
// Regenerate by re-running the fetch+build script for a league slug; do not hand-edit team names.
//
// Individual-athlete sports (tennis, golf, MMA, boxing) intentionally have no team table —
// they're resolved via player-name matching only (see lib/market-source-profiles.js).

export const LEAGUE_META = {
  nba: { sport: 'basketball', leagueSlug: 'nba', subreddit: 'nba' },
  nfl: { sport: 'football', leagueSlug: 'nfl', subreddit: 'nfl' },
  mlb: { sport: 'baseball', leagueSlug: 'mlb', subreddit: 'baseball' },
  nhl: { sport: 'hockey', leagueSlug: 'nhl', subreddit: 'hockey' },
  mls: { sport: 'soccer', leagueSlug: 'usa.1', subreddit: 'MLS' },
  prem: { sport: 'soccer', leagueSlug: 'eng.1', subreddit: 'PremierLeague' },
  laliga: { sport: 'soccer', leagueSlug: 'esp.1', subreddit: 'LaLiga' },
  bundesliga: { sport: 'soccer', leagueSlug: 'ger.1', subreddit: 'Bundesliga' },
  seriea: { sport: 'soccer', leagueSlug: 'ita.1', subreddit: 'seriea' },
  ligue1: { sport: 'soccer', leagueSlug: 'fra.1', subreddit: 'Ligue1' },
};

// Individual-athlete sports: no team/league resolution, just a general ESPN feed + subreddit.
// boxing has no working ESPN site-API league slug (confirmed via direct request), so it gets
// espnSlug: null and falls back to Google News (sports-domain-restricted) + r/Boxing only.
export const INDIVIDUAL_SPORTS = {
  tennis: { espnSport: 'tennis', espnSlug: 'atp', subreddit: 'tennis' },
  golf:   { espnSport: 'golf', espnSlug: 'pga', subreddit: 'golf' },
  mma:    { espnSport: 'mma', espnSlug: 'ufc', subreddit: 'MMA' },
  boxing: { espnSport: 'boxing', espnSlug: null, subreddit: 'Boxing' },
};

// alias (lowercase) -> { league, espnAbbr, full }
export const TEAM_LOOKUP = {
  '1. fc union berlin': { league: 'bundesliga', espnAbbr: 'FCU', full: '1. FC Union Berlin' },
  '49ers': { league: 'nfl', espnAbbr: 'SF', full: 'San Francisco 49ers' },
  '76ers': { league: 'nba', espnAbbr: 'PHI', full: 'Philadelphia 76ers' },
  'ac milan': { league: 'seriea', espnAbbr: 'MIL', full: 'AC Milan' },
  'afc bournemouth': { league: 'prem', espnAbbr: 'BOU', full: 'AFC Bournemouth' },
  'aj auxerre': { league: 'ligue1', espnAbbr: 'AUX', full: 'AJ Auxerre' },
  'alavés': { league: 'laliga', espnAbbr: 'ALA', full: 'Alavés' },
  'anaheim': { league: 'nhl', espnAbbr: 'ANA', full: 'Anaheim Ducks' },
  'anaheim ducks': { league: 'nhl', espnAbbr: 'ANA', full: 'Anaheim Ducks' },
  'angels': { league: 'mlb', espnAbbr: 'LAA', full: 'Los Angeles Angels' },
  'angers': { league: 'ligue1', espnAbbr: 'ANG', full: 'Angers' },
  'arizona': { league: 'nfl', espnAbbr: 'ARI', full: 'Arizona Cardinals' },
  'arizona cardinals': { league: 'nfl', espnAbbr: 'ARI', full: 'Arizona Cardinals' },
  'arizona diamondbacks': { league: 'mlb', espnAbbr: 'ARI', full: 'Arizona Diamondbacks' },
  'arsenal': { league: 'prem', espnAbbr: 'ARS', full: 'Arsenal' },
  'as monaco': { league: 'ligue1', espnAbbr: 'MON', full: 'AS Monaco' },
  'as roma': { league: 'seriea', espnAbbr: 'ROMA', full: 'AS Roma' },
  'aston villa': { league: 'prem', espnAbbr: 'AVL', full: 'Aston Villa' },
  'astros': { league: 'mlb', espnAbbr: 'HOU', full: 'Houston Astros' },
  'atalanta': { league: 'seriea', espnAbbr: 'ATA', full: 'Atalanta' },
  'athletic': { league: 'laliga', espnAbbr: 'ATH', full: 'Athletic Club' },
  'athletic club': { league: 'laliga', espnAbbr: 'ATH', full: 'Athletic Club' },
  'athletics': { league: 'mlb', espnAbbr: 'ATH', full: 'Athletics' },
  'atlanta': { league: 'nba', espnAbbr: 'ATL', full: 'Atlanta Hawks' },
  'atlanta braves': { league: 'mlb', espnAbbr: 'ATL', full: 'Atlanta Braves' },
  'atlanta falcons': { league: 'nfl', espnAbbr: 'ATL', full: 'Atlanta Falcons' },
  'atlanta hawks': { league: 'nba', espnAbbr: 'ATL', full: 'Atlanta Hawks' },
  'atlanta united fc': { league: 'mls', espnAbbr: 'ATL', full: 'Atlanta United FC' },
  'atlético': { league: 'laliga', espnAbbr: 'ATM', full: 'Atlético Madrid' },
  'atlético madrid': { league: 'laliga', espnAbbr: 'ATM', full: 'Atlético Madrid' },
  'augsburg': { league: 'bundesliga', espnAbbr: 'FCA', full: 'FC Augsburg' },
  'austin': { league: 'mls', espnAbbr: 'ATX', full: 'Austin FC' },
  'austin fc': { league: 'mls', espnAbbr: 'ATX', full: 'Austin FC' },
  'auxerre': { league: 'ligue1', espnAbbr: 'AUX', full: 'AJ Auxerre' },
  'avalanche': { league: 'nhl', espnAbbr: 'COL', full: 'Colorado Avalanche' },
  'baltimore': { league: 'nfl', espnAbbr: 'BAL', full: 'Baltimore Ravens' },
  'baltimore orioles': { league: 'mlb', espnAbbr: 'BAL', full: 'Baltimore Orioles' },
  'baltimore ravens': { league: 'nfl', espnAbbr: 'BAL', full: 'Baltimore Ravens' },
  'barcelona': { league: 'laliga', espnAbbr: 'BAR', full: 'Barcelona' },
  'barça': { league: 'laliga', espnAbbr: 'BAR', full: 'Barcelona' },
  'bayer leverkusen': { league: 'bundesliga', espnAbbr: 'B04', full: 'Bayer Leverkusen' },
  'bayern': { league: 'bundesliga', espnAbbr: 'MUN', full: 'Bayern Munich' },
  'bayern munich': { league: 'bundesliga', espnAbbr: 'MUN', full: 'Bayern Munich' },
  'bears': { league: 'nfl', espnAbbr: 'CHI', full: 'Chicago Bears' },
  'bengals': { league: 'nfl', espnAbbr: 'CIN', full: 'Cincinnati Bengals' },
  'betis': { league: 'laliga', espnAbbr: 'BET', full: 'Real Betis' },
  'bills': { league: 'nfl', espnAbbr: 'BUF', full: 'Buffalo Bills' },
  'black cats': { league: 'prem', espnAbbr: 'SUN', full: 'Sunderland' },
  'blackhawks': { league: 'nhl', espnAbbr: 'CHI', full: 'Chicago Blackhawks' },
  'blue jackets': { league: 'nhl', espnAbbr: 'CBJ', full: 'Columbus Blue Jackets' },
  'blue jays': { league: 'mlb', espnAbbr: 'TOR', full: 'Toronto Blue Jays' },
  'blues': { league: 'nhl', espnAbbr: 'STL', full: 'St. Louis Blues' },
  'bologna': { league: 'seriea', espnAbbr: 'BOL', full: 'Bologna' },
  'borussia dortmund': { league: 'bundesliga', espnAbbr: 'DOR', full: 'Borussia Dortmund' },
  'borussia mönchengladbach': { league: 'bundesliga', espnAbbr: 'BMG', full: 'Borussia Mönchengladbach' },
  'boston': { league: 'nba', espnAbbr: 'BOS', full: 'Boston Celtics' },
  'boston bruins': { league: 'nhl', espnAbbr: 'BOS', full: 'Boston Bruins' },
  'boston celtics': { league: 'nba', espnAbbr: 'BOS', full: 'Boston Celtics' },
  'boston red sox': { league: 'mlb', espnAbbr: 'BOS', full: 'Boston Red Sox' },
  'bournemouth': { league: 'prem', espnAbbr: 'BOU', full: 'AFC Bournemouth' },
  'braves': { league: 'mlb', espnAbbr: 'ATL', full: 'Atlanta Braves' },
  'bremen': { league: 'bundesliga', espnAbbr: 'SVW', full: 'Werder Bremen' },
  'brentford': { league: 'prem', espnAbbr: 'BRE', full: 'Brentford' },
  'brest': { league: 'ligue1', espnAbbr: 'BRE', full: 'Brest' },
  'brewers': { league: 'mlb', espnAbbr: 'MIL', full: 'Milwaukee Brewers' },
  'brighton': { league: 'prem', espnAbbr: 'BHA', full: 'Brighton & Hove Albion' },
  'brighton & hove albion': { league: 'prem', espnAbbr: 'BHA', full: 'Brighton & Hove Albion' },
  'broncos': { league: 'nfl', espnAbbr: 'DEN', full: 'Denver Broncos' },
  'brooklyn': { league: 'nba', espnAbbr: 'BKN', full: 'Brooklyn Nets' },
  'brooklyn nets': { league: 'nba', espnAbbr: 'BKN', full: 'Brooklyn Nets' },
  'browns': { league: 'nfl', espnAbbr: 'CLE', full: 'Cleveland Browns' },
  'bruins': { league: 'nhl', espnAbbr: 'BOS', full: 'Boston Bruins' },
  'buccaneers': { league: 'nfl', espnAbbr: 'TB', full: 'Tampa Bay Buccaneers' },
  'bucks': { league: 'nba', espnAbbr: 'MIL', full: 'Milwaukee Bucks' },
  'buffalo': { league: 'nfl', espnAbbr: 'BUF', full: 'Buffalo Bills' },
  'buffalo bills': { league: 'nfl', espnAbbr: 'BUF', full: 'Buffalo Bills' },
  'buffalo sabres': { league: 'nhl', espnAbbr: 'BUF', full: 'Buffalo Sabres' },
  'bulls': { league: 'nba', espnAbbr: 'CHI', full: 'Chicago Bulls' },
  'c palace': { league: 'prem', espnAbbr: 'CRY', full: 'Crystal Palace' },
  'cagliari': { league: 'seriea', espnAbbr: 'CAG', full: 'Cagliari' },
  'calgary': { league: 'nhl', espnAbbr: 'CGY', full: 'Calgary Flames' },
  'calgary flames': { league: 'nhl', espnAbbr: 'CGY', full: 'Calgary Flames' },
  'canadiens': { league: 'nhl', espnAbbr: 'MTL', full: 'Montreal Canadiens' },
  'canucks': { league: 'nhl', espnAbbr: 'VAN', full: 'Vancouver Canucks' },
  'capitals': { league: 'nhl', espnAbbr: 'WSH', full: 'Washington Capitals' },
  'cardinals': { league: 'nfl', espnAbbr: 'ARI', full: 'Arizona Cardinals' },
  'carolina': { league: 'nfl', espnAbbr: 'CAR', full: 'Carolina Panthers' },
  'carolina hurricanes': { league: 'nhl', espnAbbr: 'CAR', full: 'Carolina Hurricanes' },
  'carolina panthers': { league: 'nfl', espnAbbr: 'CAR', full: 'Carolina Panthers' },
  'cavaliers': { league: 'nba', espnAbbr: 'CLE', full: 'Cleveland Cavaliers' },
  'celta vigo': { league: 'laliga', espnAbbr: 'CEL', full: 'Celta Vigo' },
  'celtics': { league: 'nba', espnAbbr: 'BOS', full: 'Boston Celtics' },
  'cf montréal': { league: 'mls', espnAbbr: 'MTL', full: 'CF Montréal' },
  'chargers': { league: 'nfl', espnAbbr: 'LAC', full: 'Los Angeles Chargers' },
  'charlotte': { league: 'nba', espnAbbr: 'CHA', full: 'Charlotte Hornets' },
  'charlotte fc': { league: 'mls', espnAbbr: 'CLT', full: 'Charlotte FC' },
  'charlotte hornets': { league: 'nba', espnAbbr: 'CHA', full: 'Charlotte Hornets' },
  'chelsea': { league: 'prem', espnAbbr: 'CHE', full: 'Chelsea' },
  'chicago': { league: 'nba', espnAbbr: 'CHI', full: 'Chicago Bulls' },
  'chicago bears': { league: 'nfl', espnAbbr: 'CHI', full: 'Chicago Bears' },
  'chicago blackhawks': { league: 'nhl', espnAbbr: 'CHI', full: 'Chicago Blackhawks' },
  'chicago bulls': { league: 'nba', espnAbbr: 'CHI', full: 'Chicago Bulls' },
  'chicago cubs': { league: 'mlb', espnAbbr: 'CHC', full: 'Chicago Cubs' },
  'chicago fire fc': { league: 'mls', espnAbbr: 'CHI', full: 'Chicago Fire FC' },
  'chicago white sox': { league: 'mlb', espnAbbr: 'CHW', full: 'Chicago White Sox' },
  'chiefs': { league: 'nfl', espnAbbr: 'KC', full: 'Kansas City Chiefs' },
  'cincinnati': { league: 'nfl', espnAbbr: 'CIN', full: 'Cincinnati Bengals' },
  'cincinnati bengals': { league: 'nfl', espnAbbr: 'CIN', full: 'Cincinnati Bengals' },
  'cincinnati reds': { league: 'mlb', espnAbbr: 'CIN', full: 'Cincinnati Reds' },
  'cleveland': { league: 'nba', espnAbbr: 'CLE', full: 'Cleveland Cavaliers' },
  'cleveland browns': { league: 'nfl', espnAbbr: 'CLE', full: 'Cleveland Browns' },
  'cleveland cavaliers': { league: 'nba', espnAbbr: 'CLE', full: 'Cleveland Cavaliers' },
  'cleveland guardians': { league: 'mlb', espnAbbr: 'CLE', full: 'Cleveland Guardians' },
  'clippers': { league: 'nba', espnAbbr: 'LAC', full: 'LA Clippers' },
  'cologne': { league: 'bundesliga', espnAbbr: 'KOE', full: 'FC Cologne' },
  'colorado': { league: 'mlb', espnAbbr: 'COL', full: 'Colorado Rockies' },
  'colorado avalanche': { league: 'nhl', espnAbbr: 'COL', full: 'Colorado Avalanche' },
  'colorado rapids': { league: 'mls', espnAbbr: 'COL', full: 'Colorado Rapids' },
  'colorado rockies': { league: 'mlb', espnAbbr: 'COL', full: 'Colorado Rockies' },
  'colts': { league: 'nfl', espnAbbr: 'IND', full: 'Indianapolis Colts' },
  'columbus': { league: 'nhl', espnAbbr: 'CBJ', full: 'Columbus Blue Jackets' },
  'columbus blue jackets': { league: 'nhl', espnAbbr: 'CBJ', full: 'Columbus Blue Jackets' },
  'columbus crew': { league: 'mls', espnAbbr: 'CLB', full: 'Columbus Crew' },
  'commanders': { league: 'nfl', espnAbbr: 'WSH', full: 'Washington Commanders' },
  'como': { league: 'seriea', espnAbbr: 'COMO', full: 'Como' },
  'coventry': { league: 'prem', espnAbbr: 'COV', full: 'Coventry City' },
  'coventry city': { league: 'prem', espnAbbr: 'COV', full: 'Coventry City' },
  'cowboys': { league: 'nfl', espnAbbr: 'DAL', full: 'Dallas Cowboys' },
  'crew': { league: 'mls', espnAbbr: 'CLB', full: 'Columbus Crew' },
  'crystal palace': { league: 'prem', espnAbbr: 'CRY', full: 'Crystal Palace' },
  'cubs': { league: 'mlb', espnAbbr: 'CHC', full: 'Chicago Cubs' },
  'd.c. united': { league: 'mls', espnAbbr: 'DC', full: 'D.C. United' },
  'dallas': { league: 'nba', espnAbbr: 'DAL', full: 'Dallas Mavericks' },
  'dallas cowboys': { league: 'nfl', espnAbbr: 'DAL', full: 'Dallas Cowboys' },
  'dallas mavericks': { league: 'nba', espnAbbr: 'DAL', full: 'Dallas Mavericks' },
  'dallas stars': { league: 'nhl', espnAbbr: 'DAL', full: 'Dallas Stars' },
  'denver': { league: 'nba', espnAbbr: 'DEN', full: 'Denver Nuggets' },
  'denver broncos': { league: 'nfl', espnAbbr: 'DEN', full: 'Denver Broncos' },
  'denver nuggets': { league: 'nba', espnAbbr: 'DEN', full: 'Denver Nuggets' },
  'deportivo': { league: 'laliga', espnAbbr: 'DEP', full: 'Deportivo' },
  'detroit': { league: 'nba', espnAbbr: 'DET', full: 'Detroit Pistons' },
  'detroit lions': { league: 'nfl', espnAbbr: 'DET', full: 'Detroit Lions' },
  'detroit pistons': { league: 'nba', espnAbbr: 'DET', full: 'Detroit Pistons' },
  'detroit red wings': { league: 'nhl', espnAbbr: 'DET', full: 'Detroit Red Wings' },
  'detroit tigers': { league: 'mlb', espnAbbr: 'DET', full: 'Detroit Tigers' },
  'devils': { league: 'nhl', espnAbbr: 'NJ', full: 'New Jersey Devils' },
  'diamondbacks': { league: 'mlb', espnAbbr: 'ARI', full: 'Arizona Diamondbacks' },
  'dodgers': { league: 'mlb', espnAbbr: 'LAD', full: 'Los Angeles Dodgers' },
  'dolphins': { league: 'nfl', espnAbbr: 'MIA', full: 'Miami Dolphins' },
  'dortmund': { league: 'bundesliga', espnAbbr: 'DOR', full: 'Borussia Dortmund' },
  'ducks': { league: 'nhl', espnAbbr: 'ANA', full: 'Anaheim Ducks' },
  'dynamo': { league: 'mls', espnAbbr: 'HOU', full: 'Houston Dynamo FC' },
  'eagles': { league: 'nfl', espnAbbr: 'PHI', full: 'Philadelphia Eagles' },
  'earthquakes': { league: 'mls', espnAbbr: 'SJ', full: 'San Jose Earthquakes' },
  'edmonton': { league: 'nhl', espnAbbr: 'EDM', full: 'Edmonton Oilers' },
  'edmonton oilers': { league: 'nhl', espnAbbr: 'EDM', full: 'Edmonton Oilers' },
  'eintracht frankfurt': { league: 'bundesliga', espnAbbr: 'SGE', full: 'Eintracht Frankfurt' },
  'elche': { league: 'laliga', espnAbbr: 'ELC', full: 'Elche' },
  'elversberg': { league: 'bundesliga', espnAbbr: 'ELV', full: 'SV Elversberg' },
  'espanyol': { league: 'laliga', espnAbbr: 'ESP', full: 'Espanyol' },
  'everton': { league: 'prem', espnAbbr: 'EVE', full: 'Everton' },
  'falcons': { league: 'nfl', espnAbbr: 'ATL', full: 'Atlanta Falcons' },
  'fc augsburg': { league: 'bundesliga', espnAbbr: 'FCA', full: 'FC Augsburg' },
  'fc cincinnati': { league: 'mls', espnAbbr: 'CIN', full: 'FC Cincinnati' },
  'fc cologne': { league: 'bundesliga', espnAbbr: 'KOE', full: 'FC Cologne' },
  'fc dallas': { league: 'mls', espnAbbr: 'DAL', full: 'FC Dallas' },
  'fiorentina': { league: 'seriea', espnAbbr: 'FIO', full: 'Fiorentina' },
  'fire': { league: 'mls', espnAbbr: 'CHI', full: 'Chicago Fire FC' },
  'flames': { league: 'nhl', espnAbbr: 'CGY', full: 'Calgary Flames' },
  'florida': { league: 'nhl', espnAbbr: 'FLA', full: 'Florida Panthers' },
  'florida panthers': { league: 'nhl', espnAbbr: 'FLA', full: 'Florida Panthers' },
  'flyers': { league: 'nhl', espnAbbr: 'PHI', full: 'Philadelphia Flyers' },
  'frankfurt': { league: 'bundesliga', espnAbbr: 'SGE', full: 'Eintracht Frankfurt' },
  'freiburg': { league: 'bundesliga', espnAbbr: 'SCF', full: 'SC Freiburg' },
  'frosinone': { league: 'seriea', espnAbbr: 'FRO', full: 'Frosinone' },
  'fulham': { league: 'prem', espnAbbr: 'FUL', full: 'Fulham' },
  'galaxy': { league: 'mls', espnAbbr: 'LA', full: 'LA Galaxy' },
  'genoa': { league: 'seriea', espnAbbr: 'GEN', full: 'Genoa' },
  'getafe': { league: 'laliga', espnAbbr: 'GET', full: 'Getafe' },
  'giants': { league: 'nfl', espnAbbr: 'NYG', full: 'New York Giants' },
  'gladbach': { league: 'bundesliga', espnAbbr: 'BMG', full: 'Borussia Mönchengladbach' },
  'golden knights': { league: 'nhl', espnAbbr: 'VGK', full: 'Vegas Golden Knights' },
  'golden state': { league: 'nba', espnAbbr: 'GS', full: 'Golden State Warriors' },
  'golden state warriors': { league: 'nba', espnAbbr: 'GS', full: 'Golden State Warriors' },
  'green bay': { league: 'nfl', espnAbbr: 'GB', full: 'Green Bay Packers' },
  'green bay packers': { league: 'nfl', espnAbbr: 'GB', full: 'Green Bay Packers' },
  'grizzlies': { league: 'nba', espnAbbr: 'MEM', full: 'Memphis Grizzlies' },
  'guardians': { league: 'mlb', espnAbbr: 'CLE', full: 'Cleveland Guardians' },
  'gunners': { league: 'prem', espnAbbr: 'ARS', full: 'Arsenal' },
  'hamburg': { league: 'bundesliga', espnAbbr: 'HSV', full: 'Hamburg SV' },
  'hamburg sv': { league: 'bundesliga', espnAbbr: 'HSV', full: 'Hamburg SV' },
  'hawks': { league: 'nba', espnAbbr: 'ATL', full: 'Atlanta Hawks' },
  'heat': { league: 'nba', espnAbbr: 'MIA', full: 'Miami Heat' },
  'hoffenheim': { league: 'bundesliga', espnAbbr: 'TSG', full: 'TSG Hoffenheim' },
  'hornets': { league: 'nba', espnAbbr: 'CHA', full: 'Charlotte Hornets' },
  'houston': { league: 'nba', espnAbbr: 'HOU', full: 'Houston Rockets' },
  'houston astros': { league: 'mlb', espnAbbr: 'HOU', full: 'Houston Astros' },
  'houston dynamo fc': { league: 'mls', espnAbbr: 'HOU', full: 'Houston Dynamo FC' },
  'houston rockets': { league: 'nba', espnAbbr: 'HOU', full: 'Houston Rockets' },
  'houston texans': { league: 'nfl', espnAbbr: 'HOU', full: 'Houston Texans' },
  'hull': { league: 'prem', espnAbbr: 'HUL', full: 'Hull City' },
  'hull city': { league: 'prem', espnAbbr: 'HUL', full: 'Hull City' },
  'hurricanes': { league: 'nhl', espnAbbr: 'CAR', full: 'Carolina Hurricanes' },
  'impact': { league: 'mls', espnAbbr: 'MTL', full: 'CF Montréal' },
  'indiana': { league: 'nba', espnAbbr: 'IND', full: 'Indiana Pacers' },
  'indiana pacers': { league: 'nba', espnAbbr: 'IND', full: 'Indiana Pacers' },
  'indianapolis': { league: 'nfl', espnAbbr: 'IND', full: 'Indianapolis Colts' },
  'indianapolis colts': { league: 'nfl', espnAbbr: 'IND', full: 'Indianapolis Colts' },
  'inter miami cf': { league: 'mls', espnAbbr: 'MIA', full: 'Inter Miami CF' },
  'inter milan': { league: 'seriea', espnAbbr: 'INT', full: 'Internazionale' },
  'internazionale': { league: 'seriea', espnAbbr: 'INT', full: 'Internazionale' },
  'ipswich': { league: 'prem', espnAbbr: 'IPS', full: 'Ipswich Town' },
  'ipswich town': { league: 'prem', espnAbbr: 'IPS', full: 'Ipswich Town' },
  'islanders': { league: 'nhl', espnAbbr: 'NYI', full: 'New York Islanders' },
  'jacksonville': { league: 'nfl', espnAbbr: 'JAX', full: 'Jacksonville Jaguars' },
  'jacksonville jaguars': { league: 'nfl', espnAbbr: 'JAX', full: 'Jacksonville Jaguars' },
  'jaguars': { league: 'nfl', espnAbbr: 'JAX', full: 'Jacksonville Jaguars' },
  'jazz': { league: 'nba', espnAbbr: 'UTAH', full: 'Utah Jazz' },
  'jets': { league: 'nfl', espnAbbr: 'NYJ', full: 'New York Jets' },
  'juventus': { league: 'seriea', espnAbbr: 'JUV', full: 'Juventus' },
  'kansas city': { league: 'nfl', espnAbbr: 'KC', full: 'Kansas City Chiefs' },
  'kansas city chiefs': { league: 'nfl', espnAbbr: 'KC', full: 'Kansas City Chiefs' },
  'kansas city royals': { league: 'mlb', espnAbbr: 'KC', full: 'Kansas City Royals' },
  'kings': { league: 'nba', espnAbbr: 'SAC', full: 'Sacramento Kings' },
  'knicks': { league: 'nba', espnAbbr: 'NY', full: 'New York Knicks' },
  'kraken': { league: 'nhl', espnAbbr: 'SEA', full: 'Seattle Kraken' },
  'la clippers': { league: 'nba', espnAbbr: 'LAC', full: 'LA Clippers' },
  'la galaxy': { league: 'mls', espnAbbr: 'LA', full: 'LA Galaxy' },
  'lafc': { league: 'mls', espnAbbr: 'LAFC', full: 'LAFC' },
  'lakers': { league: 'nba', espnAbbr: 'LAL', full: 'Los Angeles Lakers' },
  'las vegas': { league: 'nfl', espnAbbr: 'LV', full: 'Las Vegas Raiders' },
  'las vegas raiders': { league: 'nfl', espnAbbr: 'LV', full: 'Las Vegas Raiders' },
  'lazio': { league: 'seriea', espnAbbr: 'LAZ', full: 'Lazio' },
  'le havre ac': { league: 'ligue1', espnAbbr: 'HAC', full: 'Le Havre AC' },
  'le mans': { league: 'ligue1', espnAbbr: 'MNS', full: 'Le Mans' },
  'lecce': { league: 'seriea', espnAbbr: 'LEC', full: 'Lecce' },
  'leeds': { league: 'prem', espnAbbr: 'LEE', full: 'Leeds United' },
  'leeds united': { league: 'prem', espnAbbr: 'LEE', full: 'Leeds United' },
  'lens': { league: 'ligue1', espnAbbr: 'RCL', full: 'Lens' },
  'levante': { league: 'laliga', espnAbbr: 'LEV', full: 'Levante' },
  'leverkusen': { league: 'bundesliga', espnAbbr: 'B04', full: 'Bayer Leverkusen' },
  'lightning': { league: 'nhl', espnAbbr: 'TB', full: 'Tampa Bay Lightning' },
  'lille': { league: 'ligue1', espnAbbr: 'LILL', full: 'Lille' },
  'lions': { league: 'nfl', espnAbbr: 'DET', full: 'Detroit Lions' },
  'liverpool': { league: 'prem', espnAbbr: 'LIV', full: 'Liverpool' },
  'lorient': { league: 'ligue1', espnAbbr: 'LOR', full: 'Lorient' },
  'los angeles': { league: 'nba', espnAbbr: 'LAL', full: 'Los Angeles Lakers' },
  'los angeles angels': { league: 'mlb', espnAbbr: 'LAA', full: 'Los Angeles Angels' },
  'los angeles chargers': { league: 'nfl', espnAbbr: 'LAC', full: 'Los Angeles Chargers' },
  'los angeles dodgers': { league: 'mlb', espnAbbr: 'LAD', full: 'Los Angeles Dodgers' },
  'los angeles kings': { league: 'nhl', espnAbbr: 'LA', full: 'Los Angeles Kings' },
  'los angeles lakers': { league: 'nba', espnAbbr: 'LAL', full: 'Los Angeles Lakers' },
  'los angeles rams': { league: 'nfl', espnAbbr: 'LAR', full: 'Los Angeles Rams' },
  'lyon': { league: 'ligue1', espnAbbr: 'LYON', full: 'Lyon' },
  'magic': { league: 'nba', espnAbbr: 'ORL', full: 'Orlando Magic' },
  'magpies': { league: 'prem', espnAbbr: 'NEW', full: 'Newcastle United' },
  'mainz': { league: 'bundesliga', espnAbbr: 'M05', full: 'Mainz' },
  'mammoth': { league: 'nhl', espnAbbr: 'UTAH', full: 'Utah Mammoth' },
  'man city': { league: 'prem', espnAbbr: 'MNC', full: 'Manchester City' },
  'man united': { league: 'prem', espnAbbr: 'MAN', full: 'Manchester United' },
  'manchester city': { league: 'prem', espnAbbr: 'MNC', full: 'Manchester City' },
  'manchester united': { league: 'prem', espnAbbr: 'MAN', full: 'Manchester United' },
  'maple leafs': { league: 'nhl', espnAbbr: 'TOR', full: 'Toronto Maple Leafs' },
  'mariners': { league: 'mlb', espnAbbr: 'SEA', full: 'Seattle Mariners' },
  'marlins': { league: 'mlb', espnAbbr: 'MIA', full: 'Miami Marlins' },
  'marseille': { league: 'ligue1', espnAbbr: 'OLM', full: 'Marseille' },
  'mavericks': { league: 'nba', espnAbbr: 'DAL', full: 'Dallas Mavericks' },
  'memphis': { league: 'nba', espnAbbr: 'MEM', full: 'Memphis Grizzlies' },
  'memphis grizzlies': { league: 'nba', espnAbbr: 'MEM', full: 'Memphis Grizzlies' },
  'mets': { league: 'mlb', espnAbbr: 'NYM', full: 'New York Mets' },
  'miami': { league: 'nba', espnAbbr: 'MIA', full: 'Miami Heat' },
  'miami dolphins': { league: 'nfl', espnAbbr: 'MIA', full: 'Miami Dolphins' },
  'miami heat': { league: 'nba', espnAbbr: 'MIA', full: 'Miami Heat' },
  'miami marlins': { league: 'mlb', espnAbbr: 'MIA', full: 'Miami Marlins' },
  'milan': { league: 'seriea', espnAbbr: 'MIL', full: 'AC Milan' },
  'milwaukee': { league: 'nba', espnAbbr: 'MIL', full: 'Milwaukee Bucks' },
  'milwaukee brewers': { league: 'mlb', espnAbbr: 'MIL', full: 'Milwaukee Brewers' },
  'milwaukee bucks': { league: 'nba', espnAbbr: 'MIL', full: 'Milwaukee Bucks' },
  'minnesota': { league: 'nba', espnAbbr: 'MIN', full: 'Minnesota Timberwolves' },
  'minnesota timberwolves': { league: 'nba', espnAbbr: 'MIN', full: 'Minnesota Timberwolves' },
  'minnesota twins': { league: 'mlb', espnAbbr: 'MIN', full: 'Minnesota Twins' },
  'minnesota united fc': { league: 'mls', espnAbbr: 'MIN', full: 'Minnesota United FC' },
  'minnesota vikings': { league: 'nfl', espnAbbr: 'MIN', full: 'Minnesota Vikings' },
  'minnesota wild': { league: 'nhl', espnAbbr: 'MIN', full: 'Minnesota Wild' },
  'monaco': { league: 'ligue1', espnAbbr: 'MON', full: 'AS Monaco' },
  'montreal': { league: 'nhl', espnAbbr: 'MTL', full: 'Montreal Canadiens' },
  'montreal canadiens': { league: 'nhl', espnAbbr: 'MTL', full: 'Montreal Canadiens' },
  'monza': { league: 'seriea', espnAbbr: 'MON', full: 'Monza' },
  'málaga': { league: 'laliga', espnAbbr: 'MCF', full: 'Málaga' },
  'napoli': { league: 'seriea', espnAbbr: 'NAP', full: 'Napoli' },
  'nashville': { league: 'nhl', espnAbbr: 'NSH', full: 'Nashville Predators' },
  'nashville predators': { league: 'nhl', espnAbbr: 'NSH', full: 'Nashville Predators' },
  'nashville sc': { league: 'mls', espnAbbr: 'NSH', full: 'Nashville SC' },
  'nationals': { league: 'mlb', espnAbbr: 'WSH', full: 'Washington Nationals' },
  'nets': { league: 'nba', espnAbbr: 'BKN', full: 'Brooklyn Nets' },
  'new england': { league: 'nfl', espnAbbr: 'NE', full: 'New England Patriots' },
  'new england patriots': { league: 'nfl', espnAbbr: 'NE', full: 'New England Patriots' },
  'new england revolution': { league: 'mls', espnAbbr: 'NE', full: 'New England Revolution' },
  'new jersey': { league: 'nhl', espnAbbr: 'NJ', full: 'New Jersey Devils' },
  'new jersey devils': { league: 'nhl', espnAbbr: 'NJ', full: 'New Jersey Devils' },
  'new orleans': { league: 'nba', espnAbbr: 'NO', full: 'New Orleans Pelicans' },
  'new orleans pelicans': { league: 'nba', espnAbbr: 'NO', full: 'New Orleans Pelicans' },
  'new orleans saints': { league: 'nfl', espnAbbr: 'NO', full: 'New Orleans Saints' },
  'new york': { league: 'nba', espnAbbr: 'NY', full: 'New York Knicks' },
  'new york city fc': { league: 'mls', espnAbbr: 'NYC', full: 'New York City FC' },
  'new york giants': { league: 'nfl', espnAbbr: 'NYG', full: 'New York Giants' },
  'new york islanders': { league: 'nhl', espnAbbr: 'NYI', full: 'New York Islanders' },
  'new york jets': { league: 'nfl', espnAbbr: 'NYJ', full: 'New York Jets' },
  'new york knicks': { league: 'nba', espnAbbr: 'NY', full: 'New York Knicks' },
  'new york mets': { league: 'mlb', espnAbbr: 'NYM', full: 'New York Mets' },
  'new york rangers': { league: 'nhl', espnAbbr: 'NYR', full: 'New York Rangers' },
  'new york yankees': { league: 'mlb', espnAbbr: 'NYY', full: 'New York Yankees' },
  'newcastle': { league: 'prem', espnAbbr: 'NEW', full: 'Newcastle United' },
  'newcastle united': { league: 'prem', espnAbbr: 'NEW', full: 'Newcastle United' },
  'nice': { league: 'ligue1', espnAbbr: 'NICE', full: 'Nice' },
  'nottingham f.': { league: 'prem', espnAbbr: 'NFO', full: 'Nottingham Forest' },
  'nottingham forest': { league: 'prem', espnAbbr: 'NFO', full: 'Nottingham Forest' },
  'nottm forest': { league: 'prem', espnAbbr: 'NFO', full: 'Nottingham Forest' },
  'nuggets': { league: 'nba', espnAbbr: 'DEN', full: 'Denver Nuggets' },
  'nyc fc': { league: 'mls', espnAbbr: 'NYC', full: 'New York City FC' },
  'nycfc': { league: 'mls', espnAbbr: 'NYC', full: 'New York City FC' },
  'oilers': { league: 'nhl', espnAbbr: 'EDM', full: 'Edmonton Oilers' },
  'oklahoma city': { league: 'nba', espnAbbr: 'OKC', full: 'Oklahoma City Thunder' },
  'oklahoma city thunder': { league: 'nba', espnAbbr: 'OKC', full: 'Oklahoma City Thunder' },
  'orioles': { league: 'mlb', espnAbbr: 'BAL', full: 'Baltimore Orioles' },
  'orlando': { league: 'nba', espnAbbr: 'ORL', full: 'Orlando Magic' },
  'orlando city sc': { league: 'mls', espnAbbr: 'ORL', full: 'Orlando City SC' },
  'orlando magic': { league: 'nba', espnAbbr: 'ORL', full: 'Orlando Magic' },
  'osasuna': { league: 'laliga', espnAbbr: 'OSA', full: 'Osasuna' },
  'ottawa': { league: 'nhl', espnAbbr: 'OTT', full: 'Ottawa Senators' },
  'ottawa senators': { league: 'nhl', espnAbbr: 'OTT', full: 'Ottawa Senators' },
  'pacers': { league: 'nba', espnAbbr: 'IND', full: 'Indiana Pacers' },
  'packers': { league: 'nfl', espnAbbr: 'GB', full: 'Green Bay Packers' },
  'paderborn': { league: 'bundesliga', espnAbbr: 'SCP', full: 'SC Paderborn 07' },
  'padres': { league: 'mlb', espnAbbr: 'SD', full: 'San Diego Padres' },
  'panthers': { league: 'nfl', espnAbbr: 'CAR', full: 'Carolina Panthers' },
  'paris fc': { league: 'ligue1', espnAbbr: 'PAR', full: 'Paris FC' },
  'paris saint-germain': { league: 'ligue1', espnAbbr: 'PSG', full: 'Paris Saint-Germain' },
  'parma': { league: 'seriea', espnAbbr: 'PAR', full: 'Parma' },
  'patriots': { league: 'nfl', espnAbbr: 'NE', full: 'New England Patriots' },
  'pelicans': { league: 'nba', espnAbbr: 'NO', full: 'New Orleans Pelicans' },
  'penguins': { league: 'nhl', espnAbbr: 'PIT', full: 'Pittsburgh Penguins' },
  'philadelphia': { league: 'nba', espnAbbr: 'PHI', full: 'Philadelphia 76ers' },
  'philadelphia 76ers': { league: 'nba', espnAbbr: 'PHI', full: 'Philadelphia 76ers' },
  'philadelphia eagles': { league: 'nfl', espnAbbr: 'PHI', full: 'Philadelphia Eagles' },
  'philadelphia flyers': { league: 'nhl', espnAbbr: 'PHI', full: 'Philadelphia Flyers' },
  'philadelphia phillies': { league: 'mlb', espnAbbr: 'PHI', full: 'Philadelphia Phillies' },
  'philadelphia union': { league: 'mls', espnAbbr: 'PHI', full: 'Philadelphia Union' },
  'phillies': { league: 'mlb', espnAbbr: 'PHI', full: 'Philadelphia Phillies' },
  'phoenix': { league: 'nba', espnAbbr: 'PHX', full: 'Phoenix Suns' },
  'phoenix suns': { league: 'nba', espnAbbr: 'PHX', full: 'Phoenix Suns' },
  'pirates': { league: 'mlb', espnAbbr: 'PIT', full: 'Pittsburgh Pirates' },
  'pistons': { league: 'nba', espnAbbr: 'DET', full: 'Detroit Pistons' },
  'pittsburgh': { league: 'nfl', espnAbbr: 'PIT', full: 'Pittsburgh Steelers' },
  'pittsburgh penguins': { league: 'nhl', espnAbbr: 'PIT', full: 'Pittsburgh Penguins' },
  'pittsburgh pirates': { league: 'mlb', espnAbbr: 'PIT', full: 'Pittsburgh Pirates' },
  'pittsburgh steelers': { league: 'nfl', espnAbbr: 'PIT', full: 'Pittsburgh Steelers' },
  'portland': { league: 'nba', espnAbbr: 'POR', full: 'Portland Trail Blazers' },
  'portland timbers': { league: 'mls', espnAbbr: 'POR', full: 'Portland Timbers' },
  'portland trail blazers': { league: 'nba', espnAbbr: 'POR', full: 'Portland Trail Blazers' },
  'predators': { league: 'nhl', espnAbbr: 'NSH', full: 'Nashville Predators' },
  'psg': { league: 'ligue1', espnAbbr: 'PSG', full: 'Paris Saint-Germain' },
  'racing': { league: 'laliga', espnAbbr: 'RAC', full: 'Racing Santander' },
  'racing santander': { league: 'laliga', espnAbbr: 'RAC', full: 'Racing Santander' },
  'raiders': { league: 'nfl', espnAbbr: 'LV', full: 'Las Vegas Raiders' },
  'rams': { league: 'nfl', espnAbbr: 'LAR', full: 'Los Angeles Rams' },
  'rangers': { league: 'mlb', espnAbbr: 'TEX', full: 'Texas Rangers' },
  'rapids': { league: 'mls', espnAbbr: 'COL', full: 'Colorado Rapids' },
  'raptors': { league: 'nba', espnAbbr: 'TOR', full: 'Toronto Raptors' },
  'ravens': { league: 'nfl', espnAbbr: 'BAL', full: 'Baltimore Ravens' },
  'rayo': { league: 'laliga', espnAbbr: 'RAY', full: 'Rayo Vallecano' },
  'rayo vallecano': { league: 'laliga', espnAbbr: 'RAY', full: 'Rayo Vallecano' },
  'rays': { league: 'mlb', espnAbbr: 'TB', full: 'Tampa Bay Rays' },
  'rb leipzig': { league: 'bundesliga', espnAbbr: 'RBL', full: 'RB Leipzig' },
  'real betis': { league: 'laliga', espnAbbr: 'BET', full: 'Real Betis' },
  'real madrid': { league: 'laliga', espnAbbr: 'RMA', full: 'Real Madrid' },
  'real salt lake': { league: 'mls', espnAbbr: 'RSL', full: 'Real Salt Lake' },
  'real sociedad': { league: 'laliga', espnAbbr: 'RSO', full: 'Real Sociedad' },
  'red bull new york': { league: 'mls', espnAbbr: 'RBNY', full: 'Red Bull New York' },
  'red bull ny': { league: 'mls', espnAbbr: 'RBNY', full: 'Red Bull New York' },
  'red bulls': { league: 'mls', espnAbbr: 'RBNY', full: 'Red Bull New York' },
  'red devils': { league: 'prem', espnAbbr: 'MAN', full: 'Manchester United' },
  'red sox': { league: 'mlb', espnAbbr: 'BOS', full: 'Boston Red Sox' },
  'red wings': { league: 'nhl', espnAbbr: 'DET', full: 'Detroit Red Wings' },
  'reds': { league: 'mlb', espnAbbr: 'CIN', full: 'Cincinnati Reds' },
  'rennes': { league: 'ligue1', espnAbbr: 'REN', full: 'Stade Rennais' },
  'revolution': { league: 'mls', espnAbbr: 'NE', full: 'New England Revolution' },
  'rockets': { league: 'nba', espnAbbr: 'HOU', full: 'Houston Rockets' },
  'rockies': { league: 'mlb', espnAbbr: 'COL', full: 'Colorado Rockies' },
  'royals': { league: 'mlb', espnAbbr: 'KC', full: 'Kansas City Royals' },
  'sabres': { league: 'nhl', espnAbbr: 'BUF', full: 'Buffalo Sabres' },
  'sacramento': { league: 'nba', espnAbbr: 'SAC', full: 'Sacramento Kings' },
  'sacramento kings': { league: 'nba', espnAbbr: 'SAC', full: 'Sacramento Kings' },
  'saints': { league: 'nfl', espnAbbr: 'NO', full: 'New Orleans Saints' },
  'salt lake': { league: 'mls', espnAbbr: 'RSL', full: 'Real Salt Lake' },
  'san antonio': { league: 'nba', espnAbbr: 'SA', full: 'San Antonio Spurs' },
  'san antonio spurs': { league: 'nba', espnAbbr: 'SA', full: 'San Antonio Spurs' },
  'san diego': { league: 'mlb', espnAbbr: 'SD', full: 'San Diego Padres' },
  'san diego fc': { league: 'mls', espnAbbr: 'SD', full: 'San Diego FC' },
  'san diego padres': { league: 'mlb', espnAbbr: 'SD', full: 'San Diego Padres' },
  'san francisco': { league: 'nfl', espnAbbr: 'SF', full: 'San Francisco 49ers' },
  'san francisco 49ers': { league: 'nfl', espnAbbr: 'SF', full: 'San Francisco 49ers' },
  'san francisco giants': { league: 'mlb', espnAbbr: 'SF', full: 'San Francisco Giants' },
  'san jose': { league: 'nhl', espnAbbr: 'SJ', full: 'San Jose Sharks' },
  'san jose earthquakes': { league: 'mls', espnAbbr: 'SJ', full: 'San Jose Earthquakes' },
  'san jose sharks': { league: 'nhl', espnAbbr: 'SJ', full: 'San Jose Sharks' },
  'sassuolo': { league: 'seriea', espnAbbr: 'SAS', full: 'Sassuolo' },
  'sc freiburg': { league: 'bundesliga', espnAbbr: 'SCF', full: 'SC Freiburg' },
  'sc paderborn 07': { league: 'bundesliga', espnAbbr: 'SCP', full: 'SC Paderborn 07' },
  'schalke': { league: 'bundesliga', espnAbbr: 'S04', full: 'Schalke 04' },
  'schalke 04': { league: 'bundesliga', espnAbbr: 'S04', full: 'Schalke 04' },
  'seagulls': { league: 'prem', espnAbbr: 'BHA', full: 'Brighton & Hove Albion' },
  'seahawks': { league: 'nfl', espnAbbr: 'SEA', full: 'Seattle Seahawks' },
  'seattle': { league: 'nfl', espnAbbr: 'SEA', full: 'Seattle Seahawks' },
  'seattle kraken': { league: 'nhl', espnAbbr: 'SEA', full: 'Seattle Kraken' },
  'seattle mariners': { league: 'mlb', espnAbbr: 'SEA', full: 'Seattle Mariners' },
  'seattle seahawks': { league: 'nfl', espnAbbr: 'SEA', full: 'Seattle Seahawks' },
  'seattle sounders fc': { league: 'mls', espnAbbr: 'SEA', full: 'Seattle Sounders FC' },
  'senators': { league: 'nhl', espnAbbr: 'OTT', full: 'Ottawa Senators' },
  'sevilla': { league: 'laliga', espnAbbr: 'SEV', full: 'Sevilla' },
  'sharks': { league: 'nhl', espnAbbr: 'SJ', full: 'San Jose Sharks' },
  'sky blues': { league: 'prem', espnAbbr: 'MNC', full: 'Manchester City' },
  'sounders': { league: 'mls', espnAbbr: 'SEA', full: 'Seattle Sounders FC' },
  'sporting': { league: 'mls', espnAbbr: 'SKC', full: 'Sporting Kansas City' },
  'sporting kansas city': { league: 'mls', espnAbbr: 'SKC', full: 'Sporting Kansas City' },
  'spurs': { league: 'nba', espnAbbr: 'SA', full: 'San Antonio Spurs' },
  'st. louis': { league: 'mlb', espnAbbr: 'STL', full: 'St. Louis Cardinals' },
  'st. louis blues': { league: 'nhl', espnAbbr: 'STL', full: 'St. Louis Blues' },
  'st. louis cardinals': { league: 'mlb', espnAbbr: 'STL', full: 'St. Louis Cardinals' },
  'st. louis city sc': { league: 'mls', espnAbbr: 'STL', full: 'St. Louis CITY SC' },
  'stade rennais': { league: 'ligue1', espnAbbr: 'REN', full: 'Stade Rennais' },
  'stars': { league: 'nhl', espnAbbr: 'DAL', full: 'Dallas Stars' },
  'steelers': { league: 'nfl', espnAbbr: 'PIT', full: 'Pittsburgh Steelers' },
  'strasbourg': { league: 'ligue1', espnAbbr: 'STR', full: 'Strasbourg' },
  'stuttgart': { league: 'bundesliga', espnAbbr: 'VFB', full: 'VfB Stuttgart' },
  'sunderland': { league: 'prem', espnAbbr: 'SUN', full: 'Sunderland' },
  'suns': { league: 'nba', espnAbbr: 'PHX', full: 'Phoenix Suns' },
  'sv elversberg': { league: 'bundesliga', espnAbbr: 'ELV', full: 'SV Elversberg' },
  'tampa bay': { league: 'nfl', espnAbbr: 'TB', full: 'Tampa Bay Buccaneers' },
  'tampa bay buccaneers': { league: 'nfl', espnAbbr: 'TB', full: 'Tampa Bay Buccaneers' },
  'tampa bay lightning': { league: 'nhl', espnAbbr: 'TB', full: 'Tampa Bay Lightning' },
  'tampa bay rays': { league: 'mlb', espnAbbr: 'TB', full: 'Tampa Bay Rays' },
  'tennessee': { league: 'nfl', espnAbbr: 'TEN', full: 'Tennessee Titans' },
  'tennessee titans': { league: 'nfl', espnAbbr: 'TEN', full: 'Tennessee Titans' },
  'texans': { league: 'nfl', espnAbbr: 'HOU', full: 'Houston Texans' },
  'texas': { league: 'mlb', espnAbbr: 'TEX', full: 'Texas Rangers' },
  'texas rangers': { league: 'mlb', espnAbbr: 'TEX', full: 'Texas Rangers' },
  'thunder': { league: 'nba', espnAbbr: 'OKC', full: 'Oklahoma City Thunder' },
  'tigers': { league: 'mlb', espnAbbr: 'DET', full: 'Detroit Tigers' },
  'timbers': { league: 'mls', espnAbbr: 'POR', full: 'Portland Timbers' },
  'timberwolves': { league: 'nba', espnAbbr: 'MIN', full: 'Minnesota Timberwolves' },
  'titans': { league: 'nfl', espnAbbr: 'TEN', full: 'Tennessee Titans' },
  'toffees': { league: 'prem', espnAbbr: 'EVE', full: 'Everton' },
  'toon': { league: 'prem', espnAbbr: 'NEW', full: 'Newcastle United' },
  'torino': { league: 'seriea', espnAbbr: 'TOR', full: 'Torino' },
  'toronto': { league: 'nba', espnAbbr: 'TOR', full: 'Toronto Raptors' },
  'toronto blue jays': { league: 'mlb', espnAbbr: 'TOR', full: 'Toronto Blue Jays' },
  'toronto fc': { league: 'mls', espnAbbr: 'TOR', full: 'Toronto FC' },
  'toronto maple leafs': { league: 'nhl', espnAbbr: 'TOR', full: 'Toronto Maple Leafs' },
  'toronto raptors': { league: 'nba', espnAbbr: 'TOR', full: 'Toronto Raptors' },
  'tottenham hotspur': { league: 'prem', espnAbbr: 'TOT', full: 'Tottenham Hotspur' },
  'toulouse': { league: 'ligue1', espnAbbr: 'TOU', full: 'Toulouse' },
  'tractor boys': { league: 'prem', espnAbbr: 'IPS', full: 'Ipswich Town' },
  'trail blazers': { league: 'nba', espnAbbr: 'POR', full: 'Portland Trail Blazers' },
  'troyes': { league: 'ligue1', espnAbbr: 'TRY', full: 'Troyes' },
  'tsg hoffenheim': { league: 'bundesliga', espnAbbr: 'TSG', full: 'TSG Hoffenheim' },
  'twins': { league: 'mlb', espnAbbr: 'MIN', full: 'Minnesota Twins' },
  'udinese': { league: 'seriea', espnAbbr: 'UDI', full: 'Udinese' },
  'union': { league: 'mls', espnAbbr: 'PHI', full: 'Philadelphia Union' },
  'union berlin': { league: 'bundesliga', espnAbbr: 'FCU', full: '1. FC Union Berlin' },
  'united': { league: 'mls', espnAbbr: 'DC', full: 'D.C. United' },
  'utah': { league: 'nba', espnAbbr: 'UTAH', full: 'Utah Jazz' },
  'utah jazz': { league: 'nba', espnAbbr: 'UTAH', full: 'Utah Jazz' },
  'utah mammoth': { league: 'nhl', espnAbbr: 'UTAH', full: 'Utah Mammoth' },
  'valencia': { league: 'laliga', espnAbbr: 'VAL', full: 'Valencia' },
  'vancouver': { league: 'nhl', espnAbbr: 'VAN', full: 'Vancouver Canucks' },
  'vancouver canucks': { league: 'nhl', espnAbbr: 'VAN', full: 'Vancouver Canucks' },
  'vancouver whitecaps': { league: 'mls', espnAbbr: 'VAN', full: 'Vancouver Whitecaps' },
  'vegas': { league: 'nhl', espnAbbr: 'VGK', full: 'Vegas Golden Knights' },
  'vegas golden knights': { league: 'nhl', espnAbbr: 'VGK', full: 'Vegas Golden Knights' },
  'venezia': { league: 'seriea', espnAbbr: 'VEN', full: 'Venezia' },
  'vfb stuttgart': { league: 'bundesliga', espnAbbr: 'VFB', full: 'VfB Stuttgart' },
  'vikings': { league: 'nfl', espnAbbr: 'MIN', full: 'Minnesota Vikings' },
  'villarreal': { league: 'laliga', espnAbbr: 'VIL', full: 'Villarreal' },
  'warriors': { league: 'nba', espnAbbr: 'GS', full: 'Golden State Warriors' },
  'washington': { league: 'nba', espnAbbr: 'WSH', full: 'Washington Wizards' },
  'washington capitals': { league: 'nhl', espnAbbr: 'WSH', full: 'Washington Capitals' },
  'washington commanders': { league: 'nfl', espnAbbr: 'WSH', full: 'Washington Commanders' },
  'washington nationals': { league: 'mlb', espnAbbr: 'WSH', full: 'Washington Nationals' },
  'washington wizards': { league: 'nba', espnAbbr: 'WSH', full: 'Washington Wizards' },
  'wearsiders': { league: 'prem', espnAbbr: 'SUN', full: 'Sunderland' },
  'werder bremen': { league: 'bundesliga', espnAbbr: 'SVW', full: 'Werder Bremen' },
  'white sox': { league: 'mlb', espnAbbr: 'CHW', full: 'Chicago White Sox' },
  'whitecaps': { league: 'mls', espnAbbr: 'VAN', full: 'Vancouver Whitecaps' },
  'wild': { league: 'nhl', espnAbbr: 'MIN', full: 'Minnesota Wild' },
  'winnipeg': { league: 'nhl', espnAbbr: 'WPG', full: 'Winnipeg Jets' },
  'winnipeg jets': { league: 'nhl', espnAbbr: 'WPG', full: 'Winnipeg Jets' },
  'wizards': { league: 'nba', espnAbbr: 'WSH', full: 'Washington Wizards' },
  'yankees': { league: 'mlb', espnAbbr: 'NYY', full: 'New York Yankees' },
};
